sudo: required
services:
  - docker

before_install:
  - docker build -t andrecamilosr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andrecamilosr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-222982162343"
  bucket_path: "docker-react"
  on:
    branch: master